### ISSUE TITLE
OSGi Settings section's step a going out of the allowed section on the page.

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-screens.en#1]
Issue in help/user-guide/kickstart-for-aem-screens.md

The text: _https://localhost:4502/system/console/configMgr/org.apache.sling.security.impl.ReferrerFilter_ is going beyond the center of the page.
![image](https://user-images.githubusercontent.com/59624839/76882586-3d66ac00-6851-11ea-8953-a4d9d0a9e750.png)

It should remain within the OSGi settings Note section and no go out of it.

[Logged by AEM Core Support]

**Comment by sukohli** [comment]
It happens only in Chrome browser, when the browser window size is 100%.

**Comment by bohnertchris** [comment]
Thank you for reporting this, @sukohli . It looks like this is an issue with code being rendered improperly inside of notes. I have passed this on to our documentation platform team for review. CQDOC-15583

**Comment by jyotikas** [comment]
The published content looks good now. Please feel free to re-open the issue if there are more concerns.
