### ISSUE TITLE
Add Troubleshooting instructions to the Tizen Player Setup

### ISSUE THREAD

**Issue by kmurugulla** [AdobeDocs/experience-manager-screens.en#19]
Issue in ./help/user-guide/tizen-player.md

Could you please add the trouble shooting the Tizen player from [wiki location] to the public facing documentation.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @kmurugulla. We will review.

**Comment by aheim0** [comment]
Thank you for contacting us, but debugging information is more appropriate for a KB article. We will pass the information on to the relevant department for them to review.
Closing this issue.
