### ISSUE TITLE
ofthedevice doesn't have space: https://docs.adobe.com/content/help/en/experience-manager-screens/user-guide/administering/installing-client/implementing-windows-player.html#ad-hoc-method

### ISSUE THREAD

**Issue by sukohli** [AdobeDocs/experience-manager-screens.en#3]
Issue in help/user-guide/implementing-windows-player.md

No space in "ofthedevice" in https://docs.adobe.com/content/help/en/experience-manager-screens/user-guide/administering/installing-client/implementing-windows-player.html#ad-hoc-method exists, to make them separate words.
Screenshot:
![image](https://user-images.githubusercontent.com/59624839/76897212-b1ad4980-6869-11ea-84b2-cae622ddef68.png)

**Comment by sukohli** [comment]
[Logged by AEM Core Support]

**Comment by jyotikas** [comment]
Issue fixed:
https://docs.adobe.com/content/help/en/experience-manager-screens/user-guide/administering/installing-client/implementing-windows-player.html
