### ISSUE TITLE
Screeenshots are not appropriate for video transcoding

### ISSUE THREAD

**Issue by BharathValse** [AdobeDocs/experience-manager-screens.en#4]
Issue in help/user-guide/troubleshoot-videos.md

Most of the screenshots are not relevant and point to OSGI console instead of Video transcoding screen http://localhost:4502/etc/dam/video.html

[Logged by Support]

**Comment by bohnertchris** [comment]
Thank you for pointing this out, @BharathValse. It looks like another artifact of our content migration to the new platform. We will get this fixed.

**Comment by bohnertchris** [comment]
CQDOC-15658

**Comment by guillaumecarlino** [comment]
Closing as CQDOC-15658 was closed.
