### ISSUE TITLE
Link to FP missing

### ISSUE THREAD

**Issue by Vishawdhaliwal** [AdobeDocs/experience-manager-screens.en#6]
Issue in help/user-guide/release-notes-fp-202001.md

Include the link to the feature pack and the FP version in release notes.

FP link is: https://experience.adobe.com/#/downloads/content/software-distribution/en/aem.html?package=%2Fcontent%2Fsoftware-distribution%2Fen%2Fdetails.html%2Fcontent%2Fdam%2Faem%2Fpublic%2Fadobe%2Fpackages%2Fcq650%2Ffeaturepack%2Fcq-6.5.0-featurepack-screens-1.0.350.zip

**Comment by guillaumecarlino** [comment]
This is fixed.
