### ISSUE TITLE
There should be a statement about there being no 'window' mode in the Windows player

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-screens.en#8]
Issue in help/user-guide/aem-screens-faqs.md

Since this is a question which is frequently asked (by me) it should be added here:
Q: How to enable window mode for the Windows player?
A: None. There is no window mode in Windows player. It's always full screen mode.

**Comment by aheim0** [comment]
Thanks for raising this, we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-16757.

**Comment by jyotikas** [comment]
thank you @johnb4 for reporting.
The FAQ is now added to AEM Screens FAQs page:
https://docs.adobe.com/content/help/en/experience-manager-screens/user-guide/troubleshooting/aem-screens-faqs.html#aem-screens-player
