### ISSUE TITLE
Please add these troubleshooting methods suggested by Screens Dev

### ISSUE THREAD

**Issue by mattlaun** [AdobeDocs/experience-manager-screens.en#9]
Issue in ./help/user-guide/aem-screens-faqs.md

While troubleshooting this ticket E-000264677
 Kalyanaraman Balasubramaniam Krishnan <kbalasub@adobe.com> suggested. The following. Please integrate into this page.

Engineering request that these initial troubleshooting steps are tried if issue persists to raise a ticket with the appropriate information including which display is used.
•        Is channel preview working?
•        Is display preview working?
•        Try registering the player as a browser extension on your laptop to that same display. Is that working? [1]
•        With the player running on your laptop go to http://localhost:24502. Do you see all the content downloaded correctly?
•        Check the asset(s) that the appropriate renditions are created and the correct rendition is being played
•        Check for any scheduled content and if the times are correct. Check the time set up in the player is correct.
•        Check the player console logs – Do you see any errors? Right click and inspect to see the console logs. If using the windows player press CTRL + ALT +I to bring up dev console to see the logs.
•        Please include the player logs when raising a ticket. (select the device, go to dashboard and click collect logs and attach that log to the ticket) – This may not be feasible with current player version they have.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked by CQDOC-17136

**Comment by jyotikas** [comment]
@mattlaun, thank you for reporting.
The troubleshooting tips for Blank Screen issue is now added to AEM Screens FAQs page:
https://experienceleague.adobe.com/docs/experience-manager-screens/user-guide/troubleshooting/aem-screens-faqs.html?lang=en#blank-screen
